- repo: https://github.com/antonbabenko/pre-commit-terraform
  sha: v1.7.3
  hooks:
    - id: terraform_fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
    - id: trailing-whitespace
    #- id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: check-added-large-files
    #- id: detect-private-key
